FROM golang:1.6
RUN go get github.com/imikushin/trash
RUN curl -sL https://get.docker.com/builds/Linux/x86_64/docker-1.9.1 > /usr/bin/docker && \
    chmod +x /usr/bin/docker
ENV DAPPER_SOURCE /go/src/github.com/rancher/longhorn-agent
ENV DAPPER_OUTPUT bin
ENV DAPPER_DOCKER_SOCKET true
ENV DAPPER_ENV TAG REPO
WORKDIR ${DAPPER_SOURCE}
ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
